# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Compatibility facade for typed W&B configuration and publication models."""

from __future__ import annotations

from measurement_tools.validation import StrictFrozenModel as StrictFrozenModel
from measurement_tools.wandb_field_policies import (
    OUTBOUND_FIELD_POLICIES as OUTBOUND_FIELD_POLICIES,
)
from measurement_tools.wandb_field_policies import (
    validate_outbound_field_policies as validate_outbound_field_policies,
)
from measurement_tools.wandb_metadata import BenchmarkMetadata as BenchmarkMetadata
from measurement_tools.wandb_metadata import ConfigMetadata as ConfigMetadata
from measurement_tools.wandb_metadata import DetectMetadata as DetectMetadata
from measurement_tools.wandb_metadata import ExecutionMetadata as ExecutionMetadata
from measurement_tools.wandb_metadata import GitMetadata as GitMetadata
from measurement_tools.wandb_metadata import ImportedRunMetadata as ImportedRunMetadata
from measurement_tools.wandb_metadata import MatrixMetadata as MatrixMetadata
from measurement_tools.wandb_metadata import ModelSourcesMetadata as ModelSourcesMetadata
from measurement_tools.wandb_metadata import ReplaceMetadata as ReplaceMetadata
from measurement_tools.wandb_metadata import RewriteMetadata as RewriteMetadata
from measurement_tools.wandb_metadata import RuntimeMetadata as RuntimeMetadata
from measurement_tools.wandb_metadata import SafeScalar as SafeScalar
from measurement_tools.wandb_metadata import SlurmJobMetadata as SlurmJobMetadata
from measurement_tools.wandb_metadata import SlurmMetadata as SlurmMetadata
from measurement_tools.wandb_metadata import SweepMetadata as SweepMetadata
from measurement_tools.wandb_metadata import WandbConfigPayload as WandbConfigPayload
from measurement_tools.wandb_metadata import WandbRunMetadata as WandbRunMetadata
from measurement_tools.wandb_metadata import WandbTag as WandbTag
from measurement_tools.wandb_metadata import WorkloadMetadata as WorkloadMetadata
from measurement_tools.wandb_metadata import WorkloadSourceMetadata as WorkloadSourceMetadata
from measurement_tools.wandb_metrics import _METRIC_TABLE_POLICY_FIELDS as _METRIC_TABLE_POLICY_FIELDS
from measurement_tools.wandb_metrics import WANDB_TABLE_ROW_MODELS as WANDB_TABLE_ROW_MODELS
from measurement_tools.wandb_metrics import EvaluationTableRow as EvaluationTableRow
from measurement_tools.wandb_metrics import ModelWorkflowTableRow as ModelWorkflowTableRow
from measurement_tools.wandb_metrics import NddWorkflowTableRow as NddWorkflowTableRow
from measurement_tools.wandb_metrics import RecordTableRow as RecordTableRow
from measurement_tools.wandb_metrics import RunTableRow as RunTableRow
from measurement_tools.wandb_metrics import StageTableRow as StageTableRow
from measurement_tools.wandb_metrics import TraceCoverageTableRow as TraceCoverageTableRow
from measurement_tools.wandb_metrics import WandbHistoryPayload as WandbHistoryPayload
from measurement_tools.wandb_metrics import WandbSummaryPayload as WandbSummaryPayload
from measurement_tools.wandb_metrics import WandbTablePayload as WandbTablePayload
from measurement_tools.wandb_metrics import WandbTableRow as WandbTableRow
from measurement_tools.wandb_metrics import _MetricTableRow as _MetricTableRow
from measurement_tools.wandb_policy import DataClass as DataClass
from measurement_tools.wandb_policy import Exposure as Exposure
from measurement_tools.wandb_policy import FieldPolicy as FieldPolicy
from measurement_tools.wandb_publication import PUBLICATION_COMPLETE_KEY as PUBLICATION_COMPLETE_KEY
from measurement_tools.wandb_publication import PUBLICATION_SEAL_DIGEST_KEY as PUBLICATION_SEAL_DIGEST_KEY
from measurement_tools.wandb_publication import WandbInitPayload as WandbInitPayload
from measurement_tools.wandb_publication import WandbPublicationState as WandbPublicationState
from measurement_tools.wandb_publication import WandbPublishPayload as WandbPublishPayload
from measurement_tools.wandb_publication import WandbPublishResult as WandbPublishResult
from measurement_tools.wandb_settings import DEFAULT_WANDB_PROJECT as DEFAULT_WANDB_PROJECT
from measurement_tools.wandb_settings import WANDB_TAG_MAX_LENGTH as WANDB_TAG_MAX_LENGTH
from measurement_tools.wandb_settings import ResolvedWandbConfig as ResolvedWandbConfig
from measurement_tools.wandb_settings import WandbInputs as WandbInputs
from measurement_tools.wandb_settings import WandbMode as WandbMode
from measurement_tools.wandb_settings import generated_wandb_tag as generated_wandb_tag
from measurement_tools.wandb_settings import is_safe_wandb_tag as is_safe_wandb_tag
from measurement_tools.wandb_settings import wandb_tag_value_is_sensitive as wandb_tag_value_is_sensitive
