# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from anonymizer.engine.schemas.detection import (
    AugmentedEntitiesSchema,
    AugmentedEntitySchema,
    EntitiesByValueSchema,
    EntitiesSchema,
    EntityByValueSchema,
    EntitySchema,
    LatentCategory,
    LatentConfidence,
    LatentEntitiesSchema,
    LatentEntitySchema,
    RawValidationDecisionSchema,
    RawValidationDecisionsSchema,
    ValidatedDecisionSchema,
    ValidatedDecisionsSchema,
    ValidationCandidateSchema,
    ValidationCandidatesSchema,
    ValidationChoice,
    ValidationDecisionSchema,
    ValidationDecisionsSchema,
    ValidationSkeletonDecisionSchema,
    ValidationSkeletonSchema,
)
from anonymizer.engine.schemas.replace import EntityReplacementMapSchema, EntityReplacementSchema
from anonymizer.engine.schemas.rewrite import (
    CombinedRiskLevel,
    Domain,
    DomainClassificationSchema,
    EntityCategory,
    EntityDispositionSchema,
    EntitySource,
    MeaningUnitAspect,
    MeaningUnitSchema,
    MeaningUnitsSchema,
    PrivacyAnswer,
    PrivacyAnswerItemSchema,
    PrivacyAnswersSchema,
    PrivacyQAPairsSchema,
    PrivacyQuestionSchema,
    ProtectionMethod,
    QACompareItemSchema,
    QACompareResultsSchema,
    QualityAnswerSchema,
    QualityAnswersSchema,
    QualityQAItemSchema,
    QualityQAPairsSchema,
    RewriteOutputSchema,
    SensitivityDispositionSchema,
    SensitivityLevel,
    StrictEntityDispositionSchema,
    StrictProtectionMethod,
    StrictSensitivityDispositionSchema,
)

__all__ = [
    "AugmentedEntitiesSchema",
    "AugmentedEntitySchema",
    "EntitiesByValueSchema",
    "EntitiesSchema",
    "EntityByValueSchema",
    "EntityReplacementMapSchema",
    "EntityReplacementSchema",
    "EntitySchema",
    "LatentCategory",
    "LatentConfidence",
    "LatentEntitiesSchema",
    "LatentEntitySchema",
    "RawValidationDecisionsSchema",
    "RawValidationDecisionSchema",
    "ValidatedDecisionsSchema",
    "ValidatedDecisionSchema",
    "ValidationCandidatesSchema",
    "ValidationCandidateSchema",
    "ValidationChoice",
    "ValidationDecisionsSchema",
    "ValidationDecisionSchema",
    "ValidationSkeletonDecisionSchema",
    "ValidationSkeletonSchema",
    # Rewrite
    "CombinedRiskLevel",
    "Domain",
    "DomainClassificationSchema",
    "EntityCategory",
    "EntityDispositionSchema",
    "EntitySource",
    "MeaningUnitAspect",
    "MeaningUnitSchema",
    "MeaningUnitsSchema",
    "PrivacyAnswer",
    "PrivacyAnswerItemSchema",
    "PrivacyAnswersSchema",
    "PrivacyQAPairsSchema",
    "PrivacyQuestionSchema",
    "ProtectionMethod",
    "QACompareItemSchema",
    "QACompareResultsSchema",
    "QualityAnswerSchema",
    "QualityAnswersSchema",
    "QualityQAItemSchema",
    "QualityQAPairsSchema",
    "RewriteOutputSchema",
    "SensitivityDispositionSchema",
    "SensitivityLevel",
    "StrictEntityDispositionSchema",
    "StrictProtectionMethod",
    "StrictSensitivityDispositionSchema",
]
