#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#MISE description="Remove coverage reports and Python cache files."

set -euo pipefail

mise run clean-pycache
rm -rf htmlcov .coverage .coverage.* .pytest_cache
