#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#MISE description="Prune remote refs and delete local branches already merged into main."

set -euo pipefail

git checkout main
git fetch --prune
git branch --merged | grep -v '^\*\|main' | xargs -n 1 git branch -d || true
