#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#MISE description="Remove Python bytecode and cache files."

set -euo pipefail

find . -type d -name __pycache__ -exec rm -rf {} +
find . -type f -name "*.pyc" -delete
