# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Canonical scalar field groups for sanitized measurement records."""

from __future__ import annotations

SCALAR_LAST_VALUE_FIELDS = (
    "mode",
    "stage",
    "status",
    "strategy",
    "attacker_model",
    "attacker_endpoint_kind",
    "reid_threshold",
)
SCALAR_ADDITIVE_FIELDS = (
    "elapsed_sec",
    "input_row_count",
    "seed_row_count",
    "output_row_count",
    "failed_record_count",
    "preview_num_records",
    "column_count",
    "observed_input_tokens",
    "observed_output_tokens",
    "observed_total_tokens",
    "observed_reasoning_tokens",
    "observed_successful_requests",
    "observed_failed_requests",
    "observed_total_requests",
    "text_length_chars",
    "text_length_tokens",
    "final_entity_count",
    "ground_truth_entity_count",
    "entity_true_positive_count",
    "entity_false_positive_count",
    "entity_false_negative_count",
    "entity_relaxed_gt_found_count",
    "entity_relaxed_detected_tp_count",
    "entity_relaxed_label_compatible_gt_found_count",
    "entity_relaxed_label_compatible_detected_tp_count",
    "replacement_count",
    "replacement_duplicate_value_count",
    "replacement_missing_final_entity_count",
    "replacement_missing_final_value_count",
    "replacement_synthetic_original_collision_count",
    "replacement_synthetic_original_collision_value_count",
    "original_value_leak_count",
    "detected_candidate_count",
    "validation_chunk_count",
    "llm_calls_estimated_total",
    "detection_invalid_entity_count",
    "type_fidelity_invalid_replacement_count",
    "relational_consistency_invalid_relation_count",
    "attribute_fidelity_invalid_entity_count",
    "traced_column_count",
    "native_trace_column_count",
    "private_trace_column_count",
    "unsupported_column_count",
    "rows_processed",
    "rows_failed",
    "reidentified_rows",
    "direct_reidentified_rows",
    "correctmatch_reidentified_rows",
    "reid_error_rows",
    "correct_guess_count",
    "incorrect_guess_count",
    "total_guess_count",
    "missing_output_rows",
)
SCALAR_AVERAGED_FIELDS = (
    "observed_failed_request_rate",
    "input_rows_per_sec",
    "output_rows_per_sec",
    "observed_tokens_per_sec",
    "observed_requests_per_sec",
    "observed_tokens_per_successful_request",
    "entity_precision",
    "entity_recall",
    "entity_f1",
    "utility_score",
    "leakage_mass",
    "weighted_leakage_rate",
    "repair_iterations",
    "reidentification_rate_pct",
    "coverage_pct",
    "mean_reid_score",
)
