name: Build notebooks
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * MON"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-python-env
        with:
          checkout: "false"
          python-version: "3.11"
      - name: Convert and execute notebooks
        run: mise run convert-notebooks
      - name: Upload notebooks as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notebooks
          path: docs/notebooks
